
project_id = "cvhdspyugfcvkrufqzrq"

[functions.process-artwork-image]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.hash-collection-password]
verify_jwt = true

[functions.verify-turnstile]
verify_jwt = false # Important: Should be callable without a user JWT during auth
# You might also need to specify import_map if you use one
# import_map = "./import_map.json" 
