
project_id = "cvhdspyugfcvkrufqzrq"

[functions.process-artwork-image]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.hash-collection-password]
verify_jwt = true

[functions.verify-turnstile]
verify_jwt = false

[functions.admin-send-password-reset]
verify_jwt = true # Ensure only authenticated users can call this
# import_map = "./import_map.json" # Uncomment if you use an import map
